### ISSUE TITLE
Lots of people don't have profile pictures

### ISSUE THREAD

**Issue by haoqizhang** [NUDelta/pair-research-meteor#12]
Should default to first name last initial if there isn't a photo entered.

see if this helps: http://stackoverflow.com/questions/92720/jquery-javascript-to-replace-broken-images

**Comment by haoqizhang** [comment]
better, to alert them of this...

**Comment by aspin** [comment]
a lot of people seem to have the default profile picture of "no profile picture" right now. got to fix that....

**Comment by aspin** [comment]
bigger fix: allow image upload and alert ppl of wrong photos via js in stackoverflow
