### ISSUE TITLE
Horse Race doesn't show when there are existing pairings already made (e.g., by accident)

### ISSUE THREAD

**Issue by haoqizhang** [NUDelta/pair-research-meteor#15]
This indicates some larger issues about what the correct taught behavior should be on the pair research page.

**Comment by aspin** [comment]
e.g. horse race doesn't need to disappear on making pairs. people also hit make pairs when they shouldn't

**Comment by aspin** [comment]
added a button to clear pairs w/o clearing everything else. Probably should look into having this delete history as wel...
