### ISSUE TITLE
Update signup email design to match new design spec

### ISSUE THREAD

**Issue by bomanimc** [NUDelta/pair-research-meteor#30]
The code for changing this is at line 465 in `imports/api/groups/methods.js`. 

Design spec laid out in section B of [this document](https://docs.google.com/document/d/1LiSZD4y7p_FD0uJD6B00BxUrrEmXwuMihl3YKYMRfQQ/edit?ts=58b7410f).

**Comment by bomanimc** [comment]
We can create a new Blaze template in `imports/ui/partials`, and a new scss stylesheet in `imports/ui/stylesheets` which should be linked in `client/main.scss`. 

After that, we can render the Blaze template with some following [the best answer on this post](http://stackoverflow.com/questions/17845932/using-dynamic-html-templates-in-meteor-emails).

**Comment by kapil1garg** [comment]
fixed in 016feca3c9c7ec2b3336dbb70544e3ed8899d45f and 7db99ef0c41ea213c92d21e6f20d37a2534269de
